version: "3.7"

services:
  web:
    build:
      context: ./tobias
      dockerfile: Dockerfile.dev
    command: gunicorn tobiasfyi.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./tobias/:/home/app/web
      - ./tobias/volumes/tobias_fyi_static_volume/:/home/app/web/static/
      - ./tobias/volumes/tobias_fyi_media_volume/:/home/app/web/media/
    expose:
      - 8000
    env_file: .env.dev
    networks:
      - backend_net

  nginx:
    build: ./nginx
    volumes:
      - ./tobias/volumes/tobias_fyi_static_volume/:/home/app/web/static/
      - ./tobias/volumes/tobias_fyi_media_volume/:/home/app/web/media/
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - backend_net

networks:
  backend_net:
