version: "3.7"

services:
  web:
    build:
      context: ./tobias
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tobias/:/usr/src/app
    ports:
      - 8000:8000
    env_file: .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: .env.db.dev

volumes:
  postgres_data:
