version: "3.7"

services:
  web:
    build:
      context: ./tobias
      dockerfile: Dockerfile.dev
    command: gunicorn tobiasfyi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./tobias/:/usr/src/app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8007:8000
    env_file: .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db.dev

volumes:
  postgres_data:
  static_volume:
  media_volume:
