# Generated by Django 3.0.4 on 2020-03-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200330_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='date',
            new_name='date_published',
        ),
    ]
