# Generated by Django 3.0.4 on 2020-06-11 02:28

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200610_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext_section', wagtail.core.blocks.RichTextBlock()), ('title_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title content', required=True)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False))])), ('section_header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(help_text='Header content', required=True)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False))])), ('image_block', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(max_length=240, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('internallinkblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('linkblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock()), ('title_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title content', required=True)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False))])), ('section_header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(help_text='Header content', required=True)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False))])), ('image_block', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(max_length=240, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('code_block', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('code', wagtail.core.blocks.TextBlock(required=True)), ('language', wagtail.core.blocks.CharBlock(required=True))])), ('link_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('internal_link_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('plot', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(max_length=240, required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('plot', wagtail.core.blocks.RawHTMLBlock(help_text='HTML to generate plot.', required=True))])), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('dataframe', wagtail.core.blocks.RawHTMLBlock()), ('blockquote', wagtail.core.blocks.BlockQuoteBlock()), ('blockquote_small', wagtail.core.blocks.BlockQuoteBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpagerelatedcontent',
            name='content',
            field=wagtail.core.fields.StreamField([('linkblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('related_content', wagtail.core.blocks.PageChooserBlock()), ('image_block', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(max_length=240, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('link', wagtail.core.blocks.URLBlock()), ('code_block', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('code', wagtail.core.blocks.TextBlock(required=True)), ('language', wagtail.core.blocks.CharBlock(required=True))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('richtext_section', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
