# Generated by Django 3.0.4 on 2020-06-18 23:10

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200610_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock()), ('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title content', required=True)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False))])), ('section_header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(help_text='Header content', required=True)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False))])), ('featured_section', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(help_text='Title to display above the featured section', max_length=255, required=False)), ('permalink', wagtail.core.blocks.CharBlock(help_text='HTML class for permalink', required=False)), ('featured_section', wagtail.core.blocks.PageChooserBlock(help_text='First featured section for the homepage. Will display up to three child items.', required=False))])), ('image', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(max_length=240, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('code', wagtail.core.blocks.TextBlock(required=True))])), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('internal_link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.URLBlock(required=False))])), ('plot', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(max_length=240, required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('plot', wagtail.core.blocks.RawHTMLBlock(help_text='HTML to generate plot.', required=True))])), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('dataframe', wagtail.core.blocks.RawHTMLBlock()), ('blockquote', wagtail.core.blocks.BlockQuoteBlock()), ('blockquote_small', wagtail.core.blocks.BlockQuoteBlock()), ('contact_section', wagtail.core.blocks.RawHTMLBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())], null=True),
        ),
    ]
